/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wordcounter;

import javax.swing.JOptionPane;

/**
 *
 * @author Aldas, Dominic Syd
 * @author Fernandez, Cassidy
 * @author Lafuente, Rafael
 * @author Macatunao, Joshua
 */
public class WordCounter extends javax.swing.JFrame {

    /**
     * Creates new form WordCounter1
     */
    public WordCounter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jOptionPane = new javax.swing.JOptionPane();
        titleLbl = new javax.swing.JButton();
        counterBtn = new javax.swing.JButton();
        characterCountOutput = new javax.swing.JTextField();
        wordCountOutput = new javax.swing.JTextField();
        paragraphCountOutput = new javax.swing.JTextField();
        characterCountLbl = new javax.swing.JLabel();
        wordCountLbl = new javax.swing.JLabel();
        paragraphCountLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputBox = new javax.swing.JTextArea();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        titleLbl.setText("Welcome to Word Counter!");
        titleLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, null, null));
        titleLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleLblActionPerformed(evt);
            }
        });

        counterBtn.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        counterBtn.setText("Count Here!");
        counterBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.darkGray, null, null));
        counterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterBtnActionPerformed(evt);
            }
        });

        characterCountOutput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        characterCountOutput.setText("0");
        characterCountOutput.setEnabled(false);
        characterCountOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterCountOutputActionPerformed(evt);
            }
        });

        wordCountOutput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        wordCountOutput.setText("0");
        wordCountOutput.setEnabled(false);

        paragraphCountOutput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        paragraphCountOutput.setText("0");
        paragraphCountOutput.setEnabled(false);

        characterCountLbl.setBackground(new java.awt.Color(204, 204, 204));
        characterCountLbl.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        characterCountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        characterCountLbl.setLabelFor(characterCountOutput);
        characterCountLbl.setText("Number of Characters: ");
        characterCountLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        wordCountLbl.setBackground(new java.awt.Color(204, 204, 204));
        wordCountLbl.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        wordCountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wordCountLbl.setLabelFor(wordCountOutput);
        wordCountLbl.setText("Number of Words: ");
        wordCountLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        paragraphCountLbl.setBackground(new java.awt.Color(204, 204, 204));
        paragraphCountLbl.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        paragraphCountLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paragraphCountLbl.setLabelFor(paragraphCountOutput);
        paragraphCountLbl.setText("Number of Paragraphs: ");
        paragraphCountLbl.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        inputBox.setBackground(new java.awt.Color(204, 204, 255));
        inputBox.setColumns(20);
        inputBox.setLineWrap(true);
        inputBox.setRows(1000);
        inputBox.setWrapStyleWord(true);
        inputBox.setMargin(new java.awt.Insets(15, 15, 15, 15));
        jScrollPane1.setViewportView(inputBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paragraphCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wordCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(characterCountOutput)
                    .addComponent(wordCountOutput, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paragraphCountOutput, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(counterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(counterBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(characterCountOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordCountOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(wordCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paragraphCountOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(paragraphCountLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void characterCountOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterCountOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_characterCountOutputActionPerformed

    private void counterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterBtnActionPerformed
        // TODO add your handling code here:
        // Declaration of counter variables
        int charCount = 0, wordCount = 0;
        
        // Get the input text
        String text = inputBox.getText();
        
        // Check if the user inputs something
        if(text.length() == 0) {
            JOptionPane.showMessageDialog(this, "Please input something!");
        } else {
            // Count the character/s, word/s, and paragraph/s
            charCount = text.length();
            wordCount = text.split("\\s+").length;
        }
        
        // Display the counts
        characterCountOutput.setText(String.valueOf(charCount));
        wordCountOutput.setText(String.valueOf(wordCount));     
    }//GEN-LAST:event_counterBtnActionPerformed

    private void titleLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleLblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordCounter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordCounter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel characterCountLbl;
    private javax.swing.JTextField characterCountOutput;
    private javax.swing.JButton counterBtn;
    private javax.swing.JTextArea inputBox;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel paragraphCountLbl;
    private javax.swing.JTextField paragraphCountOutput;
    private javax.swing.JButton titleLbl;
    private javax.swing.JLabel wordCountLbl;
    private javax.swing.JTextField wordCountOutput;
    // End of variables declaration//GEN-END:variables
}
